[sncast.dev_deployer]
account = "dev_deployer"
accounts-file = "/Users/bigu/Projects/localnet/.accounts/devnet_oz_accounts.json"
url = "http://127.0.0.1:5050"

[sncast.dev_operator]
account = "dev_operator"
accounts-file = "/Users/bigu/Projects/localnet/.accounts/devnet_oz_accounts.json"
url = "http://127.0.0.1:5050"

[sncast.dev_seeder]
account = "dev_seeder"
accounts-file = "/Users/bigu/Projects/localnet/.accounts/devnet_oz_accounts.json"
url = "http://127.0.0.1:5050"

[sncast.dev_bidder1]
account = "dev_bidder1"
accounts-file = "/Users/bigu/Projects/localnet/.accounts/devnet_oz_accounts.json"
url = "http://127.0.0.1:5050"

[sncast.dev_bidder2]
account = "dev_bidder2"
accounts-file = "/Users/bigu/Projects/localnet/.accounts/devnet_oz_accounts.json"
url = "http://127.0.0.1:5050"

[sncast.dev_publisher]
account = "dev_publisher"
accounts-file = "/Users/bigu/Projects/localnet/.accounts/devnet_oz_accounts.json"
url = "http://127.0.0.1:5050"

[sncast.main-sep]
account = "main-sep"
accounts-file = "/Users/bigu/.starknet_accounts/sepolia_accounts.json"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/ixt6dg9JuoeZ8Tt6RGcA8"

[sncast.pathnft_owner]
account = "PathNFT-owner"
accounts-file = "/Users/bigu/.starknet_accounts/sepolia_accounts.json"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/ixt6dg9JuoeZ8Tt6RGcA8"
