[package]
name = "path_test_support"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
snforge_std.workspace = true
path_interfaces.workspace = true
path_nft.workspace = true
path_minter.workspace = true
path_minter_adapter.workspace = true
pulse_adapter.workspace = true
pulse_auction.workspace = true

[dev-dependencies]
cairo_test.workspace = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
