[package]
name = "path_nft"
version.workspace = true
edition.workspace = true
author.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
path_interfaces.workspace = true
path_test_support.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true

[[test]]
name = "path_nft_unit"
test-type = "unit"
build-external-contracts = [
    "path_test_support::test_support::TestERC721Receiver",
    "path_test_support::test_support::TestPathLook",
]

[[target.lib]]

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
