[package]
name = "path_minter_adapter"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
path_minter = { workspace = true }
pulse_adapter = { workspace = true }
path_interfaces = { workspace = true }

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true
cairo_test.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true

[[test]]
name = "path_minter_adapter_unit"
test-type = "unit"

[[target.lib]]

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
